### ISSUE TITLE
Device tree and filter [4h]

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/waltz#103]
To use the device tree it is currently always necessay to click through the tree to the right device. Now there is the filter which helps, but it would very neat if one could type in filter and filtered devices appear as immediate;ly clickable list, like in instance/name/server style (eg p05/motor/eh2.01). That would make editing known servers blazing fast.

**Comment by Ingvord** [comment]
Maybe devices filter and devices tree filter should be merged.

**Comment by Ingvord** [comment]
Devices tree must be supplied with a _clever_ filter box, which will expand tree if filter matches pattern `{domain}/{family}/{member}`

**Comment by Ingvord** [comment]
Closed via #149
