### ISSUE TITLE
Feature request: Edit alias [1d]

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/waltz#104]
It would be great if it possible to edit aliases.

**Comment by Ingvord** [comment]
@feinfinger , you can do it via database device:

1. Open sys/database/2 in Test device panel
2. Filter commands by _alias_
3. Select DbPutDeviceAlias
4. enter device and desired alias as follows: `["sys/tg_test/1","my_test"]`
5. Execute command
6. Apply device filters (to force devices tree reload) - I should probably add an implicit button for this

**Comment by Ingvord** [comment]
I will think about how this can be integrated into UI

**Comment by Ingvord** [comment]
Due to #123 we can add _alias_ to device info as a tree node and make it editable

**Comment by Ingvord** [comment]
After discussion on Dec'13th 2018 it is decided to add ctx menu item to a device in the devices tree view: "Set alias"

**Comment by Ingvord** [comment]
@feinfinger ,

Once the new version will be deployed it will be possible to set device alias directly in device info panel:

![device_info_panel](https://user-images.githubusercontent.com/11678364/55506048-31440780-565d-11e9-8112-682154637f06.png)
