### ISSUE TITLE
Colorize buttons / input fields in Device Control Panel

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/waltz#133]
How about colorizing the buttons and input fields in the Device Control Panel. For example:
Attributes: Read button - light green 
                 Write and input field - light blue
Commands: Execute button and input field  - light blue

This could avoid confusion with the input field of the command/attribute filter.

**Comment by Ingvord** [comment]
Should not be an issue after #148

**Comment by Ingvord** [comment]
Closed via #148
