### ISSUE TITLE
Remove Columns

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/waltz#211]
It would be great if it were possible to remove single columns in the table view (especially from devices that were removed from the table).
Also maybe an additional list view (as the one that was previously shown) may be helpful in some cases.

**Comment by Ingvord** [comment]
@feinfinger , thank you for the issue!

Concerning removing columns in the table - there is such functionality already:

![dashboard2](https://user-images.githubusercontent.com/11678364/62141680-4835f600-b2ed-11e9-8244-28d8c995d28e.png)

Click on the  :gear: -> click on the column name -> corresponding column will be deleted:

![dashboard3](https://user-images.githubusercontent.com/11678364/62142024-e2963980-b2ed-11e9-924f-7454b616377a.png)

**Comment by Ingvord** [comment]
old dashboard has been integrated into the new widget as a profile type in #215 :

![st-pt-accommodations3](https://user-images.githubusercontent.com/11678364/62166367-412cd900-b329-11e9-8adc-72378d7e7678.png)
