### ISSUE TITLE
Bug shutter state display

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/waltz#217]
I tried to display the state of several shutters in p05/shutter/all (like BS1OffenDisplayState). When moving them into the Dashboard, all show the exact same value (i.e. the value of the last dragged in attribute) - which they shouldn't have and is different from the readout with read attribute.

**Comment by Ingvord** [comment]
@feinfinger, thanks for the reported issue!

This one is an upstream bug i.e. corresponding Tango server returns all `0`s when attributes are read in bunch (pytango script):

```python
>>> import tango;
>>> shutter = tango.DeviceProxy("tango://hzgpp05vme0:10000/p05/shutter/all")
>>> attrs = shutter.read_attributes(['ABS0OffenDisplayState','ABS0GeschlossenDisplayState', 'BS0OffenDisplayState', 'BS0GeschlossenDisplayState', 'BS1OffenDisplayState', 'BS1GeschlossenDisplayState', 'BS2OffenDisplayState','BS2GeschlossenDisplayState'])
>>> print(map(lambda attr: attr.value ,attrs))
[0, 0, 0, 0, 0, 0, 0, 0]
>>> print(shutter.read_attribute('BS0GeschlossenDisplayState').value)
3
>>>

```

**NOTE**: reading individual attribute returns `3` when in an array it is `0`

TangoRestServer reads device's attributes in one shot i.e. executing `read_attributes` hence affected by this bug. I will mark this one as `won't fix` now. Sorry
