### ISSUE TITLE
match settings tab and the tab from where these settings are

### ISSUE THREAD

**Issue by HelgaMond** [tango-controls/waltz#83]
It would be nice if the user can easily match settings tab and the tab from where these settings are.

May be make the settings tab be inside the main one... Or somehow make these two tabs be together.

![settingstab_vs_maintab](https://user-images.githubusercontent.com/27626862/36529131-79d6874a-17c8-11e8-890a-7ad22407d27d.png)

**Comment by Ingvord** [comment]
This is no longer relevant as in new releases all tango host related entities are combined:

![waltz_tabs1](https://user-images.githubusercontent.com/11678364/61299988-6e35a380-a7e1-11e9-8365-25c6d331d61e.png)

Please reopen with new description
